/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Brandon Farley (https://sketchfab.com/Farley)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/golf-ball-f536b891d32847ae8b8660ccbf398611
title: Golf Ball
*/

import React, { useRef } from 'react'
import { useGLTF, Sparkles } from '@react-three/drei'
import {useFrame} from '@react-three/fiber'

export function Custom(props) {
  
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')

  useFrame(() => {
    group.current.rotation.y += 0.01;
    
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 1, 0]}>
        <mesh geometry={nodes.Icosphere012_0.geometry} material={materials['Scene_-_Root']}>
            
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
